# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@serialport/binding-abstract-9.2.3" = {
      name = "_at_serialport_slash_binding-abstract";
      packageName = "@serialport/binding-abstract";
      version = "9.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/binding-abstract/-/binding-abstract-9.2.3.tgz";
        sha512 = "cQs9tbIlG3P0IrOWyVirqlhWuJ7Ms2Zh9m2108z6Y5UW/iVj6wEOiW8EmK9QX9jmJXYllE7wgGgvVozP5oCj3w==";
      };
    };
    "@serialport/binding-mock-9.2.4" = {
      name = "_at_serialport_slash_binding-mock";
      packageName = "@serialport/binding-mock";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/binding-mock/-/binding-mock-9.2.4.tgz";
        sha512 = "dpEhACCs44oQhh6ajJfJdvQdK38Vq0N4W6iD/gdplglDCK7qXRQCMUjJIeKdS/HSEiWkC3bwumUhUufdsOyT4g==";
      };
    };
    "@serialport/bindings-9.2.8" = {
      name = "_at_serialport_slash_bindings";
      packageName = "@serialport/bindings";
      version = "9.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/bindings/-/bindings-9.2.8.tgz";
        sha512 = "hSLxTe0tADZ3LMMGwvEJWOC/TaFQTyPeFalUCsJ1lSQ0k6bPF04JwrtB/C81GetmDBTNRY0GlD0SNtKCc7Dr5g==";
      };
    };
    "@serialport/parser-byte-length-9.2.4" = {
      name = "_at_serialport_slash_parser-byte-length";
      packageName = "@serialport/parser-byte-length";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-byte-length/-/parser-byte-length-9.2.4.tgz";
        sha512 = "sQD/iw4ZMU3xW9PLi0/GlvU6Y623jGeWecbMkO7izUo/6P7gtfv1c9ikd5h0kwL8AoAOpQA1lxdHIKox+umBUg==";
      };
    };
    "@serialport/parser-cctalk-9.2.4" = {
      name = "_at_serialport_slash_parser-cctalk";
      packageName = "@serialport/parser-cctalk";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-cctalk/-/parser-cctalk-9.2.4.tgz";
        sha512 = "T4TU5vQMwmo9AB3gQLFDWbfJXlW5jd9guEsB/nqKjFHTv0FXPdZ7DQ2TpSp8RnHWxU3GX6kYTaDO20BKzc8GPQ==";
      };
    };
    "@serialport/parser-delimiter-9.2.4" = {
      name = "_at_serialport_slash_parser-delimiter";
      packageName = "@serialport/parser-delimiter";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-delimiter/-/parser-delimiter-9.2.4.tgz";
        sha512 = "4nvTAoYAgkxFiXrkI+3CA49Yd43CODjeszh89EK+I9c8wOZ+etZduRCzINYPiy26g7zO+GRAb9FoPCsY+sYcbQ==";
      };
    };
    "@serialport/parser-inter-byte-timeout-9.2.4" = {
      name = "_at_serialport_slash_parser-inter-byte-timeout";
      packageName = "@serialport/parser-inter-byte-timeout";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-inter-byte-timeout/-/parser-inter-byte-timeout-9.2.4.tgz";
        sha512 = "SOAdvr0oBQIOCXX198hiTlxs4JTKg9j5piapw5tNq52fwDOWdbYrFneT/wN04UTMKaDrJuEvXq6T4rv4j7nJ5A==";
      };
    };
    "@serialport/parser-readline-9.2.4" = {
      name = "_at_serialport_slash_parser-readline";
      packageName = "@serialport/parser-readline";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-readline/-/parser-readline-9.2.4.tgz";
        sha512 = "Z1/qrZTQUVhNSJP1hd9YfDvq0o7d87rNwAjjRKbVpa7Qi51tG5BnKt43IV3NFMyBlVcRe0rnIb3tJu57E0SOwg==";
      };
    };
    "@serialport/parser-ready-9.2.4" = {
      name = "_at_serialport_slash_parser-ready";
      packageName = "@serialport/parser-ready";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-ready/-/parser-ready-9.2.4.tgz";
        sha512 = "Pyi94Itjl6qAURwIZr/gmZpMAyTmKXThm6vL5DoAWGQjcRHWB0gwv2TY2v7N+mQLJYUKU3cMnvnATXxHm7xjxw==";
      };
    };
    "@serialport/parser-regex-9.2.4" = {
      name = "_at_serialport_slash_parser-regex";
      packageName = "@serialport/parser-regex";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-regex/-/parser-regex-9.2.4.tgz";
        sha512 = "sI/cVvPOYz+Dbv4ZdnW16qAwvXiFf/1pGASQdbveRTlgJDdz7sRNlCBifzfTN2xljwvCTZYqiudKvDdC1TepRQ==";
      };
    };
    "@serialport/stream-9.2.4" = {
      name = "_at_serialport_slash_stream";
      packageName = "@serialport/stream";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/stream/-/stream-9.2.4.tgz";
        sha512 = "bLye8Ub4vUFQGmkh8qEqehr7SE7EJs2yDs0h9jzuL5oKi+F34CFmWkEErO8GAOQ8YNn7p6b3GxUgs+0BrHHDZQ==";
      };
    };
    "@signalk/vedirect-serial-usb-1.3.0" = {
      name = "_at_signalk_slash_vedirect-serial-usb";
      packageName = "@signalk/vedirect-serial-usb";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@signalk/vedirect-serial-usb/-/vedirect-serial-usb-1.3.0.tgz";
        sha512 = "WWTta7pgX69StppbkkUVEfPq6reMuRoIr9/04SAhmxbU8vw1LqrAP7GyEM6t13/wBDmz0Mhzggcnrqztbo2m3Q==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "bl-4.1.0" = {
      name = "bl";
      packageName = "bl";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-4.1.0.tgz";
        sha512 = "1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "chownr-1.1.4" = {
      name = "chownr";
      packageName = "chownr";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-1.1.4.tgz";
        sha512 = "jJ0bqzaylmJtVnNgzTeSOs8DPavpbYgEr/b0YL8/2GO3xJEhInFmhKMUnEJQjZumK7KXGFhUy89PrsJWlakBVg==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "detect-libc-2.0.1" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.1.tgz";
        sha512 = "463v3ZeIrcWtdgIg6vI6XUncguvr2TnGl4SzDXinkt9mSLpBJKXT3mW6xT3VQdDN11+WVs29pgvivTc4Lp8v+w==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "expand-template-2.0.3" = {
      name = "expand-template";
      packageName = "expand-template";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-template/-/expand-template-2.0.3.tgz";
        sha512 = "XYfuKMvj4O35f/pOXLObndIRvyQ+/+6AhODh+OKWj9S9498pHHn/IMszH+gt0fBCRWMNfk1ZSp5x3AifmnI2vg==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "fs-constants-1.0.0" = {
      name = "fs-constants";
      packageName = "fs-constants";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz";
        sha512 = "y6OAwoSIf7FyjMIv94u+b5rdheZEjzR63GTyZJm5qh4Bi+2YgwLCcI/fPFZkL5PSixOt6ZNKm+w+Hfp/Bciwow==";
      };
    };
    "github-from-package-0.0.0" = {
      name = "github-from-package";
      packageName = "github-from-package";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/github-from-package/-/github-from-package-0.0.0.tgz";
        sha512 = "SyHy3T1v2NUXn29OsWdxmK6RwHD+vkj3v8en8AOBZ1wBQ/hCAQ5bAQTD02kW4W9tUp/3Qh6J8r9EvntiyCmOOw==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-classic-0.5.3" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
        sha512 = "gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nan-2.17.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.17.0.tgz";
        sha512 = "2ZTgtl0nJsO0KQCjEpxcIr5D+Yv90plTitZt9JBfQvVJDS5seMl3FOvsh3+9CoYWXf/1l5OaZzzF6nDm4cagaQ==";
      };
    };
    "napi-build-utils-1.0.2" = {
      name = "napi-build-utils";
      packageName = "napi-build-utils";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/napi-build-utils/-/napi-build-utils-1.0.2.tgz";
        sha512 = "ONmRUqK7zj7DWX0D9ADe03wbwOBZxNAfF20PlGfCWQcD3+/MakShIHrMqx9YwPTfxDdF1zLeL+RGZiR9kGMLdg==";
      };
    };
    "node-abi-3.40.0" = {
      name = "node-abi";
      packageName = "node-abi";
      version = "3.40.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-abi/-/node-abi-3.40.0.tgz";
        sha512 = "zNy02qivjjRosswoYmPi8hIKJRr8MpQyeKT6qlcq/OnOgA3Rhoae+IYOqsM9V5+JnHWmxKnWOT2GxvtqdtOCXA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "package-lock.json-1.0.0" = {
      name = "package-lock.json";
      packageName = "package-lock.json";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-lock.json/-/package-lock.json-1.0.0.tgz";
        sha512 = "+yEXtNdlCs5N0Zy/9uvkifgf/RqnGu0WqP4j9Wu1Us4YReFe1YNBh2Krmf8B1xGxjpYnta63K55QP8bkafnOzA==";
      };
    };
    "prebuild-install-7.1.1" = {
      name = "prebuild-install";
      packageName = "prebuild-install";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prebuild-install/-/prebuild-install-7.1.1.tgz";
        sha512 = "jAXscXWMcCK8GgCoHOfIr0ODh5ai8mj63L2nWrjuAgXE6tDyYGnx4/8o/rCgU+B4JSyZBKbeZqzhtwtC3ovxjw==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "rc-1.2.8" = {
      name = "rc";
      packageName = "rc";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
        sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "semver-7.5.1" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.1.tgz";
        sha512 = "Wvss5ivl8TMRZXXESstBA4uR5iXgEN/VC5/sOcuXdVLzcdkz4HWetIoRfG5gb5X+ij/G9rw9YoGn3QoQ8OCSpw==";
      };
    };
    "serialport-9.2.8" = {
      name = "serialport";
      packageName = "serialport";
      version = "9.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialport/-/serialport-9.2.8.tgz";
        sha512 = "FsWpMQgSJxi93JgWl5xM1f9/Z8IjRJuaUEoHqLf8FPBLw7gMhInuHOBhI2onQufWIYPGTz3H3oGcu1nCaK1EfA==";
      };
    };
    "simple-concat-1.0.1" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz";
        sha512 = "cSFtAPtRhljv69IK0hTVZQ+OfE9nePi/rtJmw5UjHeVyVroEqJXP1sFztKUy1qU+xvz3u/sfYJLa947b7nAN2Q==";
      };
    };
    "simple-get-4.0.1" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-4.0.1.tgz";
        sha512 = "brv7p5WgH0jmQJr1ZDDfKDOSeWWg+OVypG99A/5vYGPqJ6pxiaHLy8nxtFjBA7oMa01ebA9gfh1uMCFqOuXxvA==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha512 = "4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
      };
    };
    "tar-fs-2.1.1" = {
      name = "tar-fs";
      packageName = "tar-fs";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-fs/-/tar-fs-2.1.1.tgz";
        sha512 = "V0r2Y9scmbDRLCNex/+hYzvp/zyYjvFbHPNgVTKfQvVrb6guiE/fxP+XblDNR011utopbkex2nM4dHNV6GDsng==";
      };
    };
    "tar-stream-2.2.0" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-2.2.0.tgz";
        sha512 = "ujeqbceABgwMZxEJnk2HDY2DlnUZ+9oEcb1KzTVfYHio0UE6dG71n60d8D2I4qNvleWrrXpmjpt7vZeF1LnMZQ==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha512 = "McnNiV1l8RYeY8tBgEpuodCC1mLUdbSN+CYBL7kJsJNInOP8UjDDEwdk6Mw60vdLLrr5NHKZhMAOSrR2NZuQ+w==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "shed-power-monitor";
    packageName = "shed-power-monitor";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@serialport/binding-abstract-9.2.3"
      sources."@serialport/binding-mock-9.2.4"
      sources."@serialport/bindings-9.2.8"
      sources."@serialport/parser-byte-length-9.2.4"
      sources."@serialport/parser-cctalk-9.2.4"
      sources."@serialport/parser-delimiter-9.2.4"
      sources."@serialport/parser-inter-byte-timeout-9.2.4"
      sources."@serialport/parser-readline-9.2.4"
      sources."@serialport/parser-ready-9.2.4"
      sources."@serialport/parser-regex-9.2.4"
      sources."@serialport/stream-9.2.4"
      sources."@signalk/vedirect-serial-usb-1.3.0"
      sources."base64-js-1.5.1"
      sources."bindings-1.5.0"
      sources."bl-4.1.0"
      sources."buffer-5.7.1"
      sources."chownr-1.1.4"
      sources."debug-4.3.4"
      sources."decompress-response-6.0.0"
      sources."deep-extend-0.6.0"
      sources."detect-libc-2.0.1"
      sources."end-of-stream-1.4.4"
      sources."expand-template-2.0.3"
      sources."file-uri-to-path-1.0.0"
      sources."fs-constants-1.0.0"
      sources."github-from-package-0.0.0"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."lru-cache-6.0.0"
      sources."mimic-response-3.1.0"
      sources."minimist-1.2.8"
      sources."mkdirp-classic-0.5.3"
      sources."ms-2.1.2"
      sources."nan-2.17.0"
      sources."napi-build-utils-1.0.2"
      sources."node-abi-3.40.0"
      sources."once-1.4.0"
      sources."package-lock.json-1.0.0"
      sources."prebuild-install-7.1.1"
      sources."pump-3.0.0"
      sources."rc-1.2.8"
      sources."readable-stream-3.6.2"
      sources."safe-buffer-5.2.1"
      sources."semver-7.5.1"
      sources."serialport-9.2.8"
      sources."simple-concat-1.0.1"
      sources."simple-get-4.0.1"
      sources."string_decoder-1.3.0"
      sources."strip-json-comments-2.0.1"
      sources."tar-fs-2.1.1"
      sources."tar-stream-2.2.0"
      sources."tunnel-agent-0.6.0"
      sources."util-deprecate-1.0.2"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
