{pkgs, modulesPath, ...}: {
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.loader.grub.device = "/dev/vda";
  boot.initrd.kernelModules = [ "nvme" ];
  fileSystems."/" = { device = "/dev/vda1"; fsType = "ext4"; };
  # networking config generated by nixos-infect
  networking = {
    nameservers = [
      "103.236.163.3"
      "103.236.162.12"
      "8.8.8.8"
    ];
    defaultGateway = "45.124.52.1";
    defaultGateway6 = "";
    dhcpcd.enable = false;
    usePredictableInterfaceNames = pkgs.lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address="45.124.52.135"; prefixLength=24; }
        ];
        ipv6.addresses = [
          { address="fe80::216:3eff:fee0:82ed"; prefixLength=64; }
        ];
        ipv4.routes = [ { address = "45.124.52.1"; prefixLength = 32; } ];
      };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="00:16:3e:e0:82:ed", NAME="eth0"

  '';

  boot.cleanTmpDir = true;
  zramSwap.enable = true;
  services.openssh.enable = true;
  services.openssh.passwordAuthentication = false;
}
